<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GeneralInfo\EquipmentControlledList;

class EquipmentControlledListSeeder extends Seeder
{
    public function run()
    {
        $items = [
            [
                'equipment_description' => 'Water Bag',
                'internal_code' => 'RS-NL-WB-72-01',
                'manufacturer' => 'Seaflex',
                'model_type' => 'WB35',
                'capacity_range' => '35-Ton',
                'serial_number' => '2372',
                'date_into_service' => '2011-03-01',
                'interval' => 'Pre-Use',
                'calibration_date' => null,
                'calibration_due_date' => null,
                'calibrated_by' => 'N/A',
                'recalibration_alarm' => 'Calibrated',
                'location_department' => 'Store',
                'status' => 'Active',
            ],
            [
                'equipment_description' => 'Water Bag',
                'internal_code' => 'RS-NL-WB-08-02',
                'manufacturer' => 'Water weights',
                'model_type' => 'WB35',
                'capacity_range' => '35-Ton',
                'serial_number' => 'WB3508',
                'date_into_service' => '2011-03-10',
                'interval' => 'Pre-Use',
                'calibration_date' => null,
                'calibration_due_date' => null,
                'calibrated_by' => 'N/A',
                'recalibration_alarm' => 'Calibrated',
                'location_department' => 'Store',
                'status' => 'Active',
            ],
            [
                'equipment_description' => 'Water Bag',
                'internal_code' => 'RS-NL-WB-19-03',
                'manufacturer' => 'Seaflex',
                'model_type' => 'N/A',
                'capacity_range' => '5-Ton',
                'serial_number' => '40519',
                'date_into_service' => '2021-11-01',
                'interval' => 'Pre-Use',
                'calibration_date' => null,
                'calibration_due_date' => null,
                'calibrated_by' => 'N/A',
                'recalibration_alarm' => 'Calibrated',
                'location_department' => 'Store',
                'status' => 'Active',
            ],
            [
                'equipment_description' => 'Water Bag',
                'internal_code' => 'RS-NL-WB-44-04',
                'manufacturer' => 'Seaflex',
                'model_type' => 'N/A',
                'capacity_range' => '2-Ton',
                'serial_number' => '42644',
                'date_into_service' => '2021-11-01',
                'interval' => 'Pre-Use',
                'calibration_date' => null,
                'calibration_due_date' => null,
                'calibrated_by' => 'N/A',
                'recalibration_alarm' => 'Calibrated',
                'location_department' => 'Store',
                'status' => 'Active',
            ],
            [
                'equipment_description' => 'Load Cell',
                'internal_code' => 'RS-NL-LC-13-09',
                'manufacturer' => 'Dynafore',
                'model_type' => 'JCM',
                'capacity_range' => '10-Ton',
                'serial_number' => '2010-242A',
                'date_into_service' => '2017-07-01',
                'interval' => 'Pre-Use',
                'calibration_date' => '2024-12-15',
                'calibration_due_date' => '2025-12-14',
                'calibrated_by' => 'OMEGA',
                'recalibration_alarm' => 'Re-Calibrate',
                'location_department' => 'Store',
                'status' => 'Active',
            ],
            [
                'equipment_description' => 'Load Cell',
                'internal_code' => 'RS-NL-LC-11-10',
                'manufacturer' => 'DILLON',
                'model_type' => 'EDXTREME',
                'capacity_range' => '20-Ton',
                'serial_number' => 'DEDX2700011',
                'date_into_service' => '2020-05-01',
                'interval' => 'Pre-Use',
                'calibration_date' => '2024-11-21',
                'calibration_due_date' => '2025-11-20',
                'calibrated_by' => 'OMEGA',
                'recalibration_alarm' => 'Re-Calibrate',
                'location_department' => 'Store',
                'status' => 'Active',
            ],
            [
                'equipment_description' => 'Load Cell',
                'internal_code' => 'RS-NL-LC-42-12',
                'manufacturer' => 'Water weights',
                'model_type' => 'Water weights',
                'capacity_range' => '25-Ton',
                'serial_number' => '642',
                'date_into_service' => '2018-01-01',
                'interval' => 'Pre-Use',
                'calibration_date' => '2022-07-19',
                'calibration_due_date' => '2023-07-18',
                'calibrated_by' => 'First',
                'recalibration_alarm' => 'Re-Calibrate',
                'location_department' => 'Store',
                'status' => 'Under Maintenance',
            ],
            [
                'equipment_description' => 'Load Cell',
                'internal_code' => 'RS-NL-LC-13-13',
                'manufacturer' => 'Straightpoint',
                'model_type' => 'Straightpoint',
                'capacity_range' => '50-Ton',
                'serial_number' => '16713',
                'date_into_service' => '2018-01-01',
                'interval' => 'Pre-Use/Annual',
                'calibration_date' => '2023-05-30',
                'calibration_due_date' => '2024-05-29',
                'calibrated_by' => 'NIS',
                'recalibration_alarm' => 'Re-Calibrate',
                'location_department' => 'Store',
                'status' => 'Under Calibration',
            ],
            [
                'equipment_description' => 'Flow Detector UT',
                'internal_code' => 'RS-NL-FD-05-14',
                'manufacturer' => 'India tools',
                'model_type' => 'India tools ITI-1700',
                'capacity_range' => 'N/A',
                'serial_number' => '140010005',
                'date_into_service' => '2018-10-01',
                'interval' => 'Pre-Use/Annual',
                'calibration_date' => '2023-07-22',
                'calibration_due_date' => '2024-07-20',
                'calibrated_by' => 'OMEGA',
                'recalibration_alarm' => 'Re-Calibrate',
                'location_department' => 'Store',
                'status' => 'Under Calibration',
            ],
            [
                'equipment_description' => 'UT Thickness Gauge',
                'internal_code' => 'RS-NL-UT-25-17',
                'manufacturer' => 'SIUICTS/308',
                'model_type' => 'SIUICTS/308',
                'capacity_range' => 'N/A',
                'serial_number' => '55331315025',
                'date_into_service' => null,
                'interval' => 'Pre-Use/Annual',
                'calibration_date' => null,
                'calibration_due_date' => '2000-12-29',
                'calibrated_by' => 'First',
                'recalibration_alarm' => 'Re-Calibrate',
                'location_department' => 'Store',
                'status' => 'Out of Service',
                'notes' => 'out of service',
            ],
        ];

        foreach ($items as $item) {
            EquipmentControlledList::create($item);
        }
    }
}
